#source /home/specg12-2/mc404/simulador/set_path_player.sh

file:
	# Para compilar e ligar o seu programa.
	arm-eabi-as -g faz_nada.s -o faz_nada.o
	arm-eabi-ld faz_nada.o -o faz_nada -Ttext=0x77802000 -Tdata=0x77803000


